# Grype vulnerability ignore rules
# These are known issues in first-class dependencies we intentionally include
# See: https://github.com/joshyorko/rcc/issues/67

ignore:
  # ============================================================================
  # RCC (joshyorko/rcc) - Go stdlib CVEs
  # Tracking: https://github.com/joshyorko/rcc/issues/67
  # Will be fixed when RCC is rebuilt with Go 1.23+
  # ============================================================================
  - vulnerability: CVE-2025-22871
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24790
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2023-24531
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61729
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61725
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61723
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58188
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58187
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-47907
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-4674
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-34158
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-34156
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24791
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24784
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2023-45288
    package:
      name: stdlib
      type: go-module

  # ============================================================================
  # Node.js (via mise) - glob package
  # Transitive dependency of npm/node tooling
  # ============================================================================
  - vulnerability: GHSA-5j98-mcp5-4vw2
    package:
      name: glob
      type: npm

  # ============================================================================
  # Ruby gems (via Homebrew)
  # Homebrew is built on Ruby - these are stdlib gems
  # ============================================================================
  - vulnerability: GHSA-xh69-987w-hrp8
    package:
      name: resolv
      type: gem
  - vulnerability: GHSA-mhwm-jh88-3gjf
    package:
      name: cgi
      type: gem
  - vulnerability: GHSA-gh9q-2xrm-x6qv
    package:
      name: cgi
      type: gem
