# Grype vulnerability ignore rules
# These are known issues in first-class dependencies we intentionally include
# See: https://github.com/joshyorko/rcc/issues/67

ignore:
  # ============================================================================
  # RCC (joshyorko/rcc) - Go stdlib CVEs
  # Tracking: https://github.com/joshyorko/rcc/issues/67
  # Will be fixed when RCC is rebuilt with Go 1.23+
  # ============================================================================
  - vulnerability: CVE-2025-22871
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24790
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2023-24531
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61729
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61725
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61723
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58188
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58187
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-47907
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-4674
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-34158
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-34156
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24791
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2024-24784
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2023-45288
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-68121
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61732
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-68119
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61731
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61726
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61730
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61728
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61727
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-61724
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58189
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58186
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58185
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-58183
    package:
      name: stdlib
      type: go-module
  - vulnerability: CVE-2025-47912
    package:
      name: stdlib
      type: go-module

  # ============================================================================
  # Node.js (via mise) - npm bundled/transitive packages
  # These are shipped within npm itself and update with npm releases.
  # ============================================================================
  - vulnerability: GHSA-5j98-mcp5-4vw2
    package:
      name: glob
      type: npm
  - vulnerability: GHSA-7h2j-956f-4vf2
    package:
      name: brace-expansion
      type: npm
  - vulnerability: GHSA-3ppc-4f35-3m26
    package:
      name: minimatch
      type: npm

  # ============================================================================
  # Ruby gems (via Homebrew)
  # Homebrew is built on Ruby - these are stdlib gems
  # ============================================================================
  - vulnerability: GHSA-xh69-987w-hrp8
    package:
      name: resolv
      type: gem
  - vulnerability: GHSA-mhwm-jh88-3gjf
    package:
      name: cgi
      type: gem
  - vulnerability: GHSA-gh9q-2xrm-x6qv
    package:
      name: cgi
      type: gem
  - vulnerability: GHSA-j4pr-3wm6-xx2r
    package:
      name: uri
      type: gem
  - vulnerability: GHSA-22h5-pq3x-2gf2
    package:
      name: uri
      type: gem

  # ============================================================================
  # OpenJPEG - Upstream vulnerabilities with no fix available
  # These are transitive dependencies from image processing libraries
  # Tracking: https://github.com/uclouvain/openjpeg/issues
  # ============================================================================
  - vulnerability: CVE-2023-39327
    package:
      name: openjpeg
      type: apk
  - vulnerability: CVE-2023-39328
    package:
      name: openjpeg
      type: apk
  - vulnerability: CVE-2023-39329
    package:
      name: openjpeg
      type: apk

  # ============================================================================
  # npm tar package - Bundled dependency in npm itself
  # The tar package is bundled inside npm's node_modules and updates when npm
  # releases a new version. We update npm@latest but can't control when npm
  # bundles the fixed tar version.
  # Tracking: https://github.com/npm/cli/issues
  # ============================================================================
  - vulnerability: GHSA-29xp-372q-xqph
    package:
      name: tar
      type: npm
  - vulnerability: GHSA-34x7-hfp2-rc4v
    package:
      name: tar
      type: npm
  - vulnerability: GHSA-83g3-92jg-28cx
    package:
      name: tar
      type: npm

  # ============================================================================
  # Python runtime CVEs from upstream Wolfi package feeds
  # Medium severity only; tracked and remediated via base image refreshes.
  # ============================================================================
  - vulnerability: CVE-2026-1299
  - vulnerability: CVE-2026-0865
  - vulnerability: CVE-2026-0672
  - vulnerability: CVE-2025-15367
  - vulnerability: CVE-2025-15366
  - vulnerability: CVE-2025-15282
  - vulnerability: CVE-2025-12781
  - vulnerability: CVE-2025-11468

  # ============================================================================
  # BusyBox - Wolfi base image component
  # Vulnerability in wget applet. We upgrade busybox in final stage but
  # the fix depends on upstream Wolfi package updates.
  # Tracking: https://github.com/wolfi-dev/os/issues
  # ============================================================================
  - vulnerability: CVE-2025-60876
    package:
      name: busybox
      type: apk
