queue_rules:
  - name: default

pull_request_rules:
  - name: auto-merge dependency updates when checks pass
    conditions:
      - author=renovate[bot] OR author=dependabot[bot]
      - check-success=codeql
      - "#approved-reviews-by>=1"
    actions:
      queue:
        name: default
