# Generated by Django 5.1.6 on 2025-02-16 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="intelligence_notes",
            field=models.TextField(
                blank=True, help_text="Auto-generated insights or manual annotations"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="predicted_completion",
            field=models.DateTimeField(
                blank=True,
                help_text="Machine learning driven completion estimate",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[
                    ("LOW", "Low"),
                    ("MEDIUM", "Medium"),
                    ("HIGH", "High"),
                    ("CRITICAL", "Critical"),
                ],
                default="MEDIUM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="risk_level",
            field=models.IntegerField(
                choices=[
                    (1, "Very Low"),
                    (2, "Low"),
                    (3, "Medium"),
                    (4, "High"),
                    (5, "Very High"),
                ],
                default=3,
            ),
        ),
    ]
