# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml
# Tip: Adding a link to the release notes of the packages helps maintenance and security.

channels:
  - conda-forge

dependencies:
  - python=3.13.11
  - uv=0.10.7
  - nodejs=25.2.1

  - pip:
      - requests==2.32.5
      - ruamel.yaml==0.19.1
      - click==8.3.1
      - robocorp==3.0.0
      - robocorp-truststore==0.9.1
      - pre-commit==4.5.1
      - yamllint==1.38.0
      - hadolintw==1.2.1

rccPostInstall:
  - npm install -g @devcontainers/cli
  - npm install -g prettier

variables:
  PYTHONPATH: "${ROBOT_ROOT}/src"
